### ISSUE TITLE
Abort SQL statements

### ISSUE THREAD

**Issue by collimarco** [sharpstone/rack-timeout#151]
When a timeout exception is raised, the SQL statements are not aborted and continue running on the db (e.g. PostgreSQL).

It would be better to abort those statements, both to protect the db from performance degradation (i.e. very long queries) and to protect the data consistency (since the method will not finish its execution).

You can reproduce that easily by running this command inside a controller method:

```
ActiveRecord::Base.connection.execute('SELECT pg_sleep(100);')
```

**Comment by dentarg** [comment]
I think this is the same as https://github.com/sharpstone/rack-timeout/issues/30

**Comment by dentarg** [comment]
I think you should handle this with [`statement_timeout`](https://dba.stackexchange.com/questions/164419/is-it-possible-to-limit-timeout-on-postgres-server) instead of rack-timeout

**Comment by collimarco** [comment]
Thanks for the reply. However the problem is more related to rack-timeout, rather than to a global setting of the database: for example, my background jobs or any maintenance task should be able to run slow queries, so I cannot change `statement_timeout`.

**Comment by dentarg** [comment]
You can use it without setting it globally. In fact, that's the recommended way of using it.

**Comment by dentarg** [comment]
> I think this is the same as #30

Ah, not really, that issue seems about rack-timeout not doing anything in certain situations

**Comment by dentarg** [comment]
I guess this is the same as https://github.com/sharpstone/rack-timeout/issues/49 :)

**Comment by wuputah** [comment]
Yep.
