### ISSUE TITLE
Rails 6 ~ middleware isn't inserted out of the box

### ISSUE THREAD

**Issue by RaviAsnani** [sharpstone/rack-timeout#153]
Using the gem out of the box 

`gem 'rack-timeout'`

It doesn't seem to insert the middleware. Have to do it manually via an initializer. 

Using:
rack-timeout (0.5.1)
rails (6.0.0)

`rake middleware`
use Honeybadger::Rack::UserInformer
use Honeybadger::Rack::UserFeedback
use Honeybadger::Rack::ErrorNotifier
use HireFire::Middleware
use Rack::Cors
use ActionDispatch::HostAuthorization
use ActionDispatch::SSL
use Rack::Sendfile
use HerokuDeflater::ServeZippedAssets
use Rack::Deflater
use HerokuDeflater::SkipBinary
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::ActionableExceptions
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use Versionist::Middleware
use Rack::Attack
use OmniAuth::Strategies::GoogleOauth2

**Comment by DSAMPAT** [comment]
@RaviAsnani have you read the readme and followed it? Middleware is not inserted for Test Environments. Check the environment config config/initializers/rack_timeout.rb
https://github.com/sharpstone/rack-timeout#basic-usage
https://github.com/sharpstone/rack-timeout#rails-apps-manually

Is this a bug or a question? Maybe this should be on stackoverflow

**Comment by RaviAsnani** [comment]
@DSAMPAT This isn't on test environments. Same behavior on production and development.

**Comment by DSAMPAT** [comment]
@RaviAsnani Try the below
# config/initializers/rack_timeout.rb

# insert middleware wherever you want in the stack, optionally pass
# initialization arguments, or use environment variables
Rails.application.config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: 5

**Comment by RaviAsnani** [comment]
Yes, if you manually insert it, it works. But according to the doc, out of the box, the middleware should get inserted automatically, which was the case until Rails 5.

**Comment by DSAMPAT** [comment]
@wuputah Please advise.

**Comment by RaviAsnani** [comment]
Also, I tried `config.autoloader = :classic` and the same issue still persists, so it's not that.

**Comment by RaviAsnani** [comment]
Okay, so tried a few things and looks like 

https://github.com/sharpstone/rack-timeout/blob/master/lib/rack/timeout/rails.rb#L8-L10

app.config.middleware has changed to app.middleware in Rails 6. I made the change and can confirm that it works.

**Comment by RaviAsnani** [comment]
Duh! Sorry about all this. I need some coffee or sleep :p So looks like the PR to support Rails 6 just hasn't been released yet.
