### ISSUE TITLE
Conditional Timeouts

### ISSUE THREAD

**Issue by ankane** [sharpstone/rack-timeout#160]
Hey, since #110 was just closed, I added conditional timeouts to [Slowpoke](https://github.com/ankane/slowpoke). You can set the service timeout with:

```ruby
config.slowpoke.timeout = lambda do |env|
  request = Rack::Request.new(env)
  request.path.start_with?("/admin") ? 15 : 5
end
```

**Comment by wuputah** [comment]
Noted. I see you're making a new middleware object for each timeout value, which certainly isn't ideal. But, at least there's a footgun available to footgunners. :joy:
