### ISSUE TITLE
Request still running/completing after timeout?

### ISSUE THREAD

**Issue by kaoru** [sharpstone/rack-timeout#167]
Hi,

I've been trying to diagnose some weird behavior in my app - according to the logs it's continuing to run the request after the rack-timeout exception is thrown.

I'm running rack-timeout 0.6.0 on rails 6.0.3.1, on puma 4.3.5, with Ruby 2.6.6. All that is running on Heroku Performance-L dynos.

The reason I think that requests are continuing to run after rack-timeout triggers is that I'm seeing `state=timed_out` and `state=completed` for the same requests.

For example:

```
Jun 02 11:59:12 charliehr heroku/router at=error code=H12 desc="Request timeout" method=GET path="/" host=podpoint.charliehr.com request_id=b948b0a1-cf3c-486a-bc06-e16723bcd8f2 fwd="82.2.70.97" dyno=web.3 connect=0ms service=30000ms status=503 bytes=0 protocol=https
Jun 02 13:01:51 charliehr app/web.3 I, [2020-06-02T12:58:42.306464 #94]  INFO -- : source=rack-timeout id=b948b0a1-cf3c-486a-bc06-e16723bcd8f2 wait=2ms timeout=15000ms state=ready
Jun 02 13:02:06 charliehr app/web.3 E, [2020-06-02T14:02:06.645598 #94] ERROR -- : source=rack-timeout id=b948b0a1-cf3c-486a-bc06-e16723bcd8f2 wait=2ms timeout=15000ms service=3804339ms state=timed_out
Jun 02 13:02:06 charliehr app/web.3 I, [2020-06-02T14:02:06.658904 #94]  INFO -- : [b948b0a1-cf3c-486a-bc06-e16723bcd8f2] method=GET path=/ format=html controller=DashboardsController action=show status=408 error='Rack::Timeout::RequestTimeoutException: Request waited 2ms, then ran for longer than 15000ms ' duration=15024.83 view=0.00 db=4393.28 agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" params={"controller"=>"dashboards", "action"=>"show"}
Jun 02 13:02:06 charliehr app/web.3 [b948b0a1-cf3c-486a-bc06-e16723bcd8f2] Rack::Timeout::RequestTimeoutException (Request waited 2ms, then ran for longer than 15000ms ):
Jun 02 13:02:06 charliehr app/web.3 I, [2020-06-02T14:02:06.663755 #94]  INFO -- : source=rack-timeout id=b948b0a1-cf3c-486a-bc06-e16723bcd8f2 wait=2ms timeout=15000ms service=3804357ms state=completed
```

Simplifying those logs a bit they look like this:

```
11:59:12 - Heroku 30 second timeout (code H12)
13:01:51 - Rack Timeout Ready - wait=2ms timeout=15000ms
13:02:06 - Rack Timeout Timed Out - wait=2ms timeout=15000ms service=3804339ms (about 1 hour)
13:02:06 - Rails GET Request - status=408 error=Rack::Timeout::RequestTimeoutException duration=15024.83
13:02:06 - Rack Timeout Completed - wait=2ms timeout=15000ms service=3804357ms state=completed
```

Here's my `config/initializers/rack_timeout.rb`:

```ruby
if Rails.env.production?
  Rails.application.config.middleware.insert_before Rack::Runtime, Rack::Timeout, service_timeout: 15
end
```

We're using code similar to the example given in https://github.com/sharpstone/rack-timeout/issues/166#issuecomment-610138398 to return the 408 error...

```ruby
# config/environments/production.rb 

Rails.application.configure do
...
  # Adjust which responses we send for particular exceptions
  config.action_dispatch.rescue_responses["Rack::Timeout::Error"] = :request_timeout
  config.action_dispatch.rescue_responses["Rack::Timeout::RequestTimeoutException"] = :request_timeout
...
end
```

Could that be the cause? What is the correct way to set up rack-timeout to do this?

Is the new `RACK_TIMEOUT_TERM_ON_TIMEOUT` option the way to solve this?

I also thought of rescuing the exception in the ApplicationController, rendering the 408 status page, and then throwing `:abort` or `:halt` but I found conflicting documentation on which of the two would actually halt the request.  Does rack-timeout already use this technique?

Let me know if I can provide any more information. Thanks 🙏

**Comment by kaoru** [comment]
Now I have an even stranger case... the case of the 1+ hour state=completed on a redirect that finished in 1.2 seconds, and also timed out with Heroku after 30 seconds.

```
Jun 02 15:33:25 charliehr heroku/router at=error code=H12 desc="Request timeout" method=GET path="/" host=www.charliehr.com request_id=a1bfdc01-27d7-4871-9fa2-7841df3285a2 fwd="85.210.99.30,162.158.155.253" dyno=web.1 connect=0ms service=30003ms status=503 bytes=0 protocol=https
Jun 02 16:51:46 charliehr app/web.1 I, [2020-06-02T16:32:55.377136 #76]  INFO -- : source=rack-timeout id=a1bfdc01-27d7-4871-9fa2-7841df3285a2 wait=5ms timeout=15000ms state=ready
Jun 02 16:51:47 charliehr app/web.1 I, [2020-06-02T17:51:47.442820 #76]  INFO -- : [a1bfdc01-27d7-4871-9fa2-7841df3285a2] method=GET path=/ format=html controller=WelcomeController action=home status=302 duration=1287.86 view=0.00 db=626.92 location=https://bornsocial.charliehr.com/ tm_id= c_id= ip=162.158.155.253 eli=true agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36" params={"controller"=>"welcome", "action"=>"home"}
Jun 02 16:51:47 charliehr app/web.1 I, [2020-06-02T17:51:47.466354 #76]  INFO -- : source=rack-timeout id=a1bfdc01-27d7-4871-9fa2-7841df3285a2 wait=5ms timeout=15000ms service=4732089ms state=completed
```

Have you seen anything like this before?

In case it helps here's my full middleware stack:

```
use ActionDispatch::HostAuthorization
use ActionDispatch::SSL
use Rack::Sendfile
use HerokuDeflater::ServeZippedAssets
use Rack::Deflater
use HerokuDeflater::SkipBinary
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Timeout
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rack::Attack
use RequestStore::Middleware
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use Appsignal::Rack::JSExceptionCatcher
use Appsignal::Rack::RailsInstrumentation
use ActionDispatch::ActionableExceptions
use ActionDispatch::Callbacks
use ActionDispatch::Cookies
use ActionDispatch::Session::ActiveRecordStore
use ActionDispatch::Flash
use ActionDispatch::ContentSecurityPolicy::Middleware
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Rack::TempfileReaper
use Warden::Manager
use Remotipart::Middleware
use Rack::Attack
use NewRelic::Rack::AgentHooks
use ScoutApm::Middleware
run Charlie::Application.routes
```

Thanks 🙏

**Comment by schneems** [comment]
Sorry for the delayed response. Are you still seeing this issue? If you are, can you please provide me with an example app that demonstrates the problem https://www.codetriage.com/example_app. Let me know and I can re-open the issue.

**Comment by kaoru** [comment]
Hey @schneems,

Sorry for the even more delayed response than your one 😅

We are still seeing this occasionally, although not the extent that we were before. We were seeing 100s of H12 errors a day and we reduced that to 10s by upgrading to the next size of PostgreSQL database.

More important than the reduction in H12 errors was the kinds of requests we see timing out now. Previously we had requests that should've been fast timing out, whereas now we mostly only see timeouts for endpoints/pages that we expect to be slow and trigger the occasional timeout for larger customers.

But as I said, we are still seeing some odd rack-timeout behaviour for a handful of requests. For example this one from this morning:

```
Sept 14 08:38:23 charliehr heroku/router at=error code=H12 desc="Request timeout" method=POST dyno=web.3 connect=1ms service=30000ms status=503 bytes=0 protocol=https

Sept 14 11:17:47 charliehr app/web.3 I, [2020-09-14T09:37:53.612541 #97]  INFO -- : source=rack-timeout id=6df767b2-bb75-410c-9987-72230689320d wait=0ms timeout=15000ms state=ready
Sept 14 11:17:48 charliehr app/web.3 I, [2020-09-14T12:17:48.248263 #97]  INFO -- : [6df767b2-bb75-410c-9987-72230689320d] method=POST status=403 duration=613.17 view=0.45 db=187.75
Sept 14 11:17:48 charliehr app/web.3 I, [2020-09-14T12:17:48.250206 #97]  INFO -- : source=rack-timeout id=6df767b2-bb75-410c-9987-72230689320d wait=0ms timeout=15000ms service=9594638ms state=completed
```

The request timed out with an H12 at 08:38, but was still running 9594638ms (about 2.7 hours) later when it apparently completed with a 403 error.

Rails seems to think it only took duration=613.17 view=0.45 db=187.75 => 801ms

If you have access to internal Heroku support tickets you can check out my long conversation with Ryan Cross about it here: https://help.heroku.com/879279 

I'll see what I can do about setting up an example app that reproduces it.

Thanks!

**Comment by kaoru** [comment]
I tried [creating an app to reproduce this](https://github.com/kaoru/rack-timeout-weirdness-app) and... it doesn't reproduce the problem yet, it actually works exactly how I want it to (it times out after 5 seconds and shows the `public/408.html` page instead of the `public/500.html` page.)

I'll play some more with it.
