### ISSUE TITLE
Sample code for handling Rack::Timeout::Error before app enters the Rails stack

### ISSUE THREAD

**Issue by PikachuEXE** [sharpstone/rack-timeout#47]
Here is [My current way of handling](https://github.com/heroku/rack-timeout/issues/40#issuecomment-51865104)
But if the app thread has not entered rails stack yet, I cannot rescue and return 503
Which is not expected

**Comment by MrHubble** [comment]
Is this issue related to https://github.com/rails/rails/issues/1627 ?

where it is suggested:
>this ticket is probably never going to be fixed as the issue is correctly blamed on rack-timeout.
>The suggested fix is to remove rack-timeout from your Gemfile (it raises exceptions on the main thread and is completely unsafe) and then fix any long-running database requests as best you can.

**Comment by wuputah** [comment]
Regarding that issue, that advise is overblown IMO, but rack-timeout should also be considered a last resort (you should have other safeguards in place, like setting `statement_timeout` for Postgres and network-level timeouts for other services).

We also recommend against using ActiveRecord's prepared statements feature for Postgres for a number of reasons; we believe it should be off by default.

**Comment by MrHubble** [comment]
@wuputah thanks for replying. I think @schneems is hopeful that ActiveRecord's prepared statements will no longer have to be disabled in Rails 5:

>Any idea if you get the same result in Rails 5? Lots of improvements have gone into Rails5 (i.e. master) that didn't make it into 4.2. If you can reproduce the behavior in Rails 5 I think it's worth opening a new issue for this.
https://github.com/rails/rails/issues/14645#issuecomment-200539074

Do you still recommend disabling prepared statements with Rails 5?

**Comment by wuputah** [comment]
Yes.

**Comment by schneems** [comment]
Does a doc PR need to be made here? This issue was last commented 4 years ago. Let's close it.
