### ISSUE TITLE
log timeout stacktrace without abort?

### ISSUE THREAD

**Issue by nruth** [sharpstone/rack-timeout#99]
I'd like to be able to change the timeout action from abort to report-only. Is there a way to do this, e.g. just send a stacktrace of the thread to stdout, or even insert a code block to run (e.g. to fire off an email with ExceptionNotifier).

I think this would keep the debugging power, without the risk of inserting arbitrary failures?

**Comment by kch** [comment]
There isn't a way, but [this debug branch][1] I made a while ago could get you half-way there if you fork and do a bit of work on it.

[1]: https://github.com/heroku/rack-timeout/commits/trace
